
service: quotes-service

provider:
 name: aws
 runtime: python3.9
 region: us-east-1
 memorySize: 128

package:
  individually: true

plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
 wsgi:
   app: app.app
   packRequirements: false

functions:
 app:
    handler: wsgi.handler
    events:
     - http: ANY /
     - http: 'ANY {proxy+}'
    package:
      include:
        - "app.py"
      exclude:
        - "requirements.txt"
        - "package.json"
        - "package-lock.json"
        - ".serverless/**"
        - ".venv/**"
        - "node_modules/**"
